status/urls.py
from django.urls import path
from . import views

app_name = 'status'

urlpatterns = [
    path('', views.index, name='homepage'),
    path('terima/', views.terima, name='terima'),
]

story6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('status.urls'), name='homepage')
]

status/models.py
from django.db import models

# Create your models here.
class StatusModel(models.Model):
    status = models.CharField(max_length=300)
    waktu_submit = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.status

status/forms.py
from django import forms

class StatusForm(forms.Form):
    isi_status = forms.CharField(label='Status kamu', max_length=300)

status/views.py
from django.shortcuts import render
from .models import StatusModel
from .forms import StatusForm

from datetime import datetime
import pytz

# Create your views here.
def index(request):
    status_form = StatusForm()
    status_obj = StatusModel.objects.all()
    argument = {
        'status_form': status_form,
        'status_obj' : status_obj,
    }
    return render(request, 'index.html', argument)

def terima(request):
    # waktu saat submit
    datetime_now = datetime.now()

    status_form = StatusForm(request.POST)

    # ambil status dr isian
    isian_status = request.POST['isi_status']

    # buat objek StatusModel
    temp = StatusModel(
        status = isian_status,
        waktu_submit = datetime_now,
    )

    # simpen
    temp.save()

    status_obj = StatusModel.objects.all()

    # tampilin halamannya
    argument = {
        'status_form': status_form,
        'status_obj' : status_obj,
    }
    return render(request, 'index.html', argument)

status/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">    
    <link rel="stylesheet" href="{% static 'style.css' %}" >
    <title>status palsu</title>
</head>
<body>
    <div class="container">
        <div class="col justify-content-center">
            <h1 class="hello">Halo, apa kabar?</h1>
            <form method="POST" action="{% url 'status:terima' %}">
                {% csrf_token %}
                {{ status_form }}
                <input type="submit" value="Posting Statusmu" name="submit-status">
            </form>

            <table>
                {% for status in status_obj %}
                <tr>
                    <th><h3>{{ status.status }}</h3></th>
                    <td>{{ status.waktu_submit }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    
</body>
</html>